class DecisionEngine:
    """
    NeuroSync Decision Engine V2

    Purpose:
    Convert KPIs, Insights, Recommendations,
    Anomalies, Forecasts and Risks into
    prioritized executive business decisions.
    """

    def generate_decisions(
        self,
        kpis,
        insights,
        recommendations,
        anomalies,
        forecast=None,
        risk_assessment=None
    ):

        forecast = forecast or {}
        risk_assessment = risk_assessment or {}

        business_status = self._evaluate_business_health(
            kpis,
            anomalies,
            risk_assessment
        )

        health_score = self._calculate_health_score(
            kpis,
            anomalies,
            risk_assessment
        )

        decisions = []

        # =====================================
        # RECOMMENDATION DRIVEN DECISIONS
        # =====================================

        for rec in recommendations:

            
                title = rec.get(
                    "title",
                    "Business Recommendation"
                )

                impact = rec.get(
                    "impact",
                    "Medium"
                )

                confidence = rec.get(
                    "confidence",
                    75
                )

                reason = rec.get(
                    "reason",
                    "Recommendation generated by NeuroSync."
                )

                expected_impact = rec.get(
                    "expected_impact",
                    "Business improvement."
                )

                urgency = rec.get(
                    "urgency",
                    self._determine_urgency(
                        anomalies,
                        risk_assessment
                    )
                )

                risk_level = rec.get(
                    "risk",
                    risk_assessment.get(
                        "risk_level",
                        "Medium"
                    )
                )

                score = self._calculate_decision_score(
                    impact,
                    risk_level,
                    urgency,
                    confidence
                )

                decisions.append({
                    "title": title,
                    "priority": self._priority_label(score),
                    "confidence": confidence,
                    "decision_score": score,
                    "reason": reason,
                    "expected_impact": expected_impact,
                    "urgency": urgency
                })

        # =====================================
        # KPI DECISIONS
        # =====================================

        profit_margin = kpis.get(
            "profit_margin_percent",
            0
        )

        total_profit = kpis.get(
            "total_profit",
            0
        )

        if total_profit <= 0:

            score = 130

            decisions.append({
                "title": "Immediate Profit Recovery Plan",
                "priority": "Critical",
                "confidence": 95,
                "decision_score": score,
                "reason": "Business is operating at a loss.",
                "expected_impact": "Restore profitability.",
                "urgency": "Immediate"
            })

        elif profit_margin < 15:

            score = 110

            decisions.append({
                "title": "Reduce Operating Costs",
                "priority": "Critical",
                "confidence": 90,
                "decision_score": score,
                "reason": "Profit margin is below target.",
                "expected_impact": "Increase profitability.",
                "urgency": "Immediate"
            })

        elif profit_margin >= 25:

            score = 90

            decisions.append({
                "title": "Scale Growth Strategy",
                "priority": "High",
                "confidence": 88,
                "decision_score": score,
                "reason": "Business profitability is strong.",
                "expected_impact": "Accelerate growth.",
                "urgency": "Soon"
            })

        # =====================================
        # ANOMALY DECISIONS
        # =====================================

        for anomaly in anomalies:

            severity = anomaly.get(
                "severity",
                "Warning"
            )

            if severity == "Critical":

                decisions.append({
                    "title": "Immediate Business Investigation",
                    "priority": "Critical",
                    "confidence": 95,
                    "decision_score": 120,
                    "reason": anomaly.get(
                        "message",
                        ""
                    ),
                    "expected_impact": "Prevent escalation.",
                    "urgency": "Immediate"
                })

        # =====================================
        # FORECAST DECISIONS
        # =====================================

        predicted_growth = forecast.get(
            "predicted_growth",
            0
        )

        if predicted_growth < 0:

            decisions.append({
                "title": "Prepare Revenue Protection Strategy",
                "priority": "High",
                "confidence": 85,
                "decision_score": 95,
                "reason": (
                    "Forecast predicts declining growth."
                ),
                "expected_impact": (
                    "Protect future revenue."
                ),
                "urgency": "Soon"
            })

        # =====================================
        # SORT DECISIONS
        # =====================================

        decisions = sorted(
            decisions,
            key=lambda x: x["decision_score"],
            reverse=True
        )

        ranked_decisions = []

        for rank, decision in enumerate(
            decisions,
            start=1
        ):

            decision["rank"] = rank
            ranked_decisions.append(
                decision
            )

        action_plan = self._generate_action_plan(
            ranked_decisions
        )

        summary = self._generate_summary(
            business_status,
            ranked_decisions
        )

        return {
            "business_status": business_status,
            "health_score": health_score,
            "priority_decisions": ranked_decisions,
            "executive_action_plan": action_plan,
            "strategic_summary": summary
        }

    # =====================================
    # BUSINESS HEALTH
    # =====================================

    def _evaluate_business_health(
        self,
        kpis,
        anomalies,
        risk_assessment
    ):

        profit = kpis.get(
            "total_profit",
            0
        )

        risk_score = risk_assessment.get(
            "risk_score",
            0
        )

        critical_anomalies = len([
            a
            for a in anomalies
            if a.get("severity") == "Critical"
        ])

        if profit <= 0:
            return "Critical"

        if critical_anomalies >= 2:
            return "Critical"

        if risk_score >= 70:
            return "Warning"

        if profit > 0 and risk_score < 30:
            return "Growth"

        return "Healthy"

    # =====================================
    # HEALTH SCORE
    # =====================================

    def _calculate_health_score(
        self,
        kpis,
        anomalies,
        risk_assessment
    ):

        score = 100

        total_profit = kpis.get(
            "total_profit",
            0
        )

        profit_margin = kpis.get(
            "profit_margin_percent",
            0
        )

        risk_score = risk_assessment.get(
            "risk_score",
            0
        )

        # Profitability penalty

        if total_profit <= 0:

            score -= 40

        elif profit_margin < 10:

            score -= 15

        elif profit_margin < 20:

            score -= 5

        # Anomaly penalty (capped)

        score -= (
            min(len(anomalies), 10) * 2
        )

        # Risk penalty (reduced)

        score -= (
            risk_score * 0.15
        )

        return max(
            0,
            round(score)
        )

    # =====================================
    # DECISION SCORE
    # =====================================

    def _calculate_decision_score(
        self,
        impact,
        risk,
        urgency,
        confidence
    ):

        impact_map = {
            "High": 40,
            "Medium": 25,
            "Low": 10
        }

        risk_map = {
            "High": 30,
            "Medium": 20,
            "Low": 10
        }

        urgency_map = {
            "Immediate": 30,
            "Soon": 20,
            "Future": 10
        }

        confidence_score = (
            30 if confidence >= 90
            else 20 if confidence >= 75
            else 10
        )

        return (
            impact_map.get(impact, 25)
            + risk_map.get(risk, 20)
            + urgency_map.get(urgency, 20)
            + confidence_score
        )

    def _priority_label(
        self,
        score
    ):

        if score >= 120:
            return "Critical"

        if score >= 90:
            return "High"

        if score >= 70:
            return "Medium"

        return "Low"

    def _determine_urgency(
        self,
        anomalies,
        risk_assessment
    ):

        if any(
            a.get("severity") == "Critical"
            for a in anomalies
        ):
            return "Immediate"

        if risk_assessment.get(
            "risk_score",
            0
        ) > 60:
            return "Soon"

        return "Future"

    # =====================================
    # ACTION PLAN
    # =====================================

    def _generate_action_plan(
        self,
        decisions
    ):

        plan = []

        for decision in decisions:

            priority = decision.get(
                "priority",
                "Low"
            )

            timeline_map = {
                "Critical": "7 Days",
                "High": "30 Days",
                "Medium": "60 Days",
                "Low": "90 Days"
            }

            plan.append({
                "priority": decision["rank"],
                "action": decision["title"],
                "timeline": timeline_map.get(
                    priority,
                    "90 Days"
                ),
                "expected_impact": decision.get(
                    "expected_impact",
                    ""
                )
            })

        return plan

    # =====================================
    # EXECUTIVE SUMMARY
    # =====================================

    def _generate_summary(
        self,
        status,
        decisions
    ):

        top_decisions = decisions[:3]

        summary = (
            f"Business status is {status}. "
        )

        if top_decisions:

            summary += (
                "Top priorities include "
                + ", ".join(
                    d["title"]
                    for d in top_decisions
                )
                + "."
            )

        return summary