services:
  - type: web
    name: neurosync-api
    runtime: python

    buildCommand: pip install -r backend/requirements.txt

    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT

    autoDeploy: true